const categories = [
  "Abogado administrativo",
  "Abogado de Derecho de familia",
  "Abogado de lesiones personales",
  "Abogado de patentes",
  "Abogado especialista en derecho de extranjeria",
  "Abogado especialista en derecho de la tercera edad",
  "Abogado especialista en derecho de seguros",
  "Abogado especializado en derecho laboral",
  "Abogado especializado en derecho procesal",
  "Abogado especializado en planificacion patrimonial",
  "Abogado especializado en propiedad inmobiliaria",
  "Abogado especializado en quiebras y concursos",
  "Abogado especializado en seguridad social",
  "Abogado fiscal",
  "Abogado laboralista",
  "Abogado matrimonialista",
  "Abogado penalista",
  "Abrevadero de animales",
  "Academia de aleman",
  "Academia de baile",
  "Academia de bomberos",
  "Academia de caligrafia",
  "Academia de chino",
  "Academia de estetica",
  "Academia de examenes civiles",
  "Academia de frances",
  "Academia de idiomas",
  "Academia de informatica",
  "Academia de ingles",
  "Academia de policia",
  "Academia de shogi",
  "Accesorios para muebles",
  "Actuacion judicial",
  "Acuario",
  "Acupuntor",
  "Adiestrador canino",
  "Administracion de loterias",
  "Administrador de la propiedad",
  "Aeropuerto",
  "Aeropuerto internacional",
  "Aeropuerto nacional",
  "Aeropuerto regional",
  "Agencia aseguradora de automoviles",
  "Agencia de adopcion",
  "Agencia de alquiler de alojamientos para vacaciones",
  "Agencia de alquiler de apartamentos",
  "Agencia de alquiler de autobuses",
  "Agencia de alquiler de autocaravanas",
  "Agencia de alquiler de cabanas",
  "Agencia de alquiler de camiones",
  "Agencia de alquiler de coches",
  "Agencia de alquiler de condominios",
  "Agencia de alquiler de equipos",
  "Agencia de alquiler de espacios para oficinas",
  "Agencia de alquiler de furgonetas",
  "Agencia de alquiler de gruas",
  "Agencia de alquiler de motocicletas",
  "Agencia de alquiler de oficinas ejecutivas",
  "Agencia de apuestas",
  "Agencia de bienes inmuebles comerciales",
  "Agencia de colocacion",
  "Agencia de cruceros",
  "Agencia de cuidado de casas",
  "Agencia de espectaculos",
  "Agencia de excursiones en autobus",
  "Agencia de excursiones en barco",
  "Agencia de excursiones en canoa y kayak",
  "Agencia de excursiones en globo",
  "Agencia de excursiones en helicoptero",
  "Agencia de informes crediticios",
  "Agencia de marketing",
  "Agencia de modelos",
  "Agencia de noticias",
  "Agencia de prestamos",
  "Agencia de publicidad",
  "Agencia de registro de automoviles",
  "Agencia de rutas a caballo",
  "Agencia de seguros de alquiler",
  "Agencia de seguros de motocicletas",
  "Agencia de seguros de vida",
  "Agencia de seguros odontologicos",
  "Agencia de seguros para el hogar",
  "Agencia de servicios de atencion a la tercera edad",
  "Agencia de subastas inmobiliarias",
  "Agencia de talentos",
  "Agencia de viajes",
  "Agencia de viajes de buceo",
  "Agencia de viajes especializada en avistamiento de ballenas",
  "Agencia de visitas turisticas",
  "Agencia expendedora de billetes de autobus",
  "Agencia federal de asistencia tecnica",
  "Agencia inmobiliaria",
  "Agencia inmobiliaria especializada en alquileres",
  "Agente de aduanas",
  "Agente judicial",
  "Agentes inmobiliarios",
  "Agenzia Entrate",
  "Agrimensor",
  "Ala de medicina interna",
  "Albanil",
  "Albergue",
  "Alergologo",
  "Almacen",
  "Almacen de jamon serrano",
  "Almacen de registros",
  "Almazara",
  "Alojamiento",
  "Alojamiento con servicio",
  "Alojamiento de autoservicio",
  "Alojamiento en el que se admiten mascotas",
  "Alojamiento en interiores",
  "Alquiler de equipo audiovisual",
  "Alquiler de oficinas virtuales",
  "Ambulatorio",
  "Anestesista",
  "Anfiteatro",
  "Animador",
  "Aparcamiento",
  "Aparcamiento cubierto",
  "Aparcamiento de coches compartidos",
  "Aparcamiento gratuito",
  "Aparcamiento para bicicletas",
  "Aparcamiento para motos",
  "Aparcamiento publico",
  "Aparcamiento Tsukigime",
  "Aparejador",
  "Aparejador de bienes inmuebles",
  "Apartamento turistico",
  "Apicultor",
  "Arboreto",
  "Archivo",
  "Archivo militar",
  "Archivo nacional",
  "Area de descanso",
  "Area de descanso de carretera de peaje",
  "Area de eventos nauticos",
  "Area de juegos de coches en miniatura",
  "Area de pesca",
  "Area de remo",
  "Area off-road",
  "Armeria",
  "Arquitecto",
  "Arquitecto paisajista",
  "Arroceria",
  "Artesania",
  "Artesano de chocolate",
  "Artista",
  "Asador de cordero",
  "Asador japones",
  "Ascensorista",
  "Aserradero",
  "Asesor",
  "Asesor acustico",
  "Asesor audiovisual",
  "Asesor de aviacion",
  "Asesor de centrales electricas",
  "Asesor de construccion",
  "Asesor de Feng Shui",
  "Asesor de imagen",
  "Asesor de pensiones de jubilacion",
  "Asesor de prensa",
  "Asesor de proteccion contra incendios",
  "Asesor educativo",
  "Asesor en comercio internacional",
  "Asesor en ingenieria",
  "Asesor financiero",
  "Asesor fiscal",
  "Asesor medico",
  "Asesor vastu",
  "Asesoria laboral",
  "Ashram",
  "Asistencia para personas sin hogar",
  "Asistente social",
  "Asociacion agricola",
  "Asociacion de aparejadores",
  "Asociacion de arquitectos",
  "Asociacion de arrendatarios",
  "Asociacion de asesoramiento del impuesto sobre la renta",
  "Asociacion de ayuda a los estudiantes",
  "Asociacion de ayuda a los pacientes",
  "Asociacion de ecologistas",
  "Asociacion de enfermeria",
  "Asociacion de estudiantes",
  "Asociacion de fuerzas armadas",
  "Asociacion de ingenieros de puertos, canales y caminos",
  "Asociacion de ingenieros industriales",
  "Asociacion de ingenieros tecnicos industriales",
  "Asociacion de Madres y Padres de Alumnos",
  "Asociacion de notarios",
  "Asociacion de residentes",
  "Asociacion sociocultural",
  "Asociacion u organizacion",
  "Assistante Maternelle",
  "Astillero",
  "Astilleros",
  "Astrologo",
  "Atencion a personas mayores",
  "Atraccion de feria",
  "Atraccion turistica",
  "Audiologo",
  "Auditorio",
  "Auditorio filarmonico",
  "Autocine",
  "Autoescuela",
  "Autoescuela de motocicletas",
  "Autoridad portuaria",
  "Autoridad reguladora de las viviendas",
  "Autoservicio mayorista",
  "Auxiliar tecnico sanitario",
  "Avion",
  "Ayuda domestica",
  "Ayuntamiento",
  "Ayuntamiento de la localidad",
  "Balneario",
  "Balneario publico",
  "Banco",
  "Banco central",
  "Banco de alimentos",
  "Banco de inversion",
  "Banco de sangre",
  "Banda de musica",
  "Bano exterior",
  "Bano publico",
  "Bano publico adaptado para discapacitados",
  "Bano publico para hombres",
  "Bano publico para mujeres",
  "Banos publicos",
  "Bar",
  "Bar con dardos",
  "Bar con musica en directo",
  "Bar con narguiles",
  "Bar con venta de tabaco",
  "Bar de alterne",
  "Bar de salsa",
  "Bar de tapas",
  "Bar deportivo",
  "Bar gay",
  "Bar musical",
  "Bar PMU",
  "Bar restaurante",
  "Bar restaurante de ostras",
  "Barberia",
  "Base aerea",
  "Base de hidroaviones",
  "Base de las Fuerzas Armadas de los Estados Unidos",
  "Base militar",
  "Base naval",
  "Basilica",
  "Bazar",
  "Bed & Breakfast",
  "Beisbol",
  "Beneficencia",
  "Biblioteca",
  "Biblioteca de fotografias y peliculas",
  "Biblioteca infantil",
  "Biblioteca nacional",
  "Biblioteca publica",
  "Biblioteca universitaria",
  "Bingo",
  "Bocateria",
  "Bodega",
  "Bolera",
  "Boot Camp",
  "Bosque nacional",
  "Boutique",
  "Braseria",
  "Bufe de dulces y reposteria",
  "Bufe para bodas",
  "Bufe para fiestas infantiles",
  "Bufete",
  "Buffet libre",
  "Cabana de montana",
  "Cabanas de madera",
  "Cabina para llamadas de emergencia",
  "Cadena de television",
  "Cafe teatro",
  "Cafeteria",
  "Cafeteria",
  "Cafeteria apta para perros",
  "Cafeteria cosplay",
  "Caja de ahorros",
  "Cajeros automaticos",
  "Caldereria industrial",
  "Camara agraria",
  "Camara de comercio",
  "Camara de oficios",
  "Camaronicultura",
  "Campamento",
  "Campamento de ingles",
  "Campamento de refugiados",
  "Camping",
  "Camping para caravanas",
  "Campo de beisbol",
  "Campo de cricket",
  "Campo de equitacion",
  "Campo de futbol",
  "Campo de futbol americano",
  "Campo de golf",
  "Campo de golf con disco",
  "Campo de golf cubierto",
  "Campo de golf privado",
  "Campo de golf publico",
  "Campo de hockey",
  "Campo de minigolf",
  "Campo de pequenas ligas",
  "Campo de practicas de golf",
  "Campo de rugby",
  "Campo de softbol",
  "Campo de tiro",
  "Campo de tiro al plato",
  "Campo de tiro con arco",
  "Campo de voleibol",
  "Campo de voley-playa",
  "Campus corporativo",
  "Cancha de baloncesto",
  "Cancha de bochas",
  "Cancha de futbol sala",
  "Canodromo",
  "Cantera",
  "Cantero",
  "Capilla",
  "Capilla nupcial",
  "Cardiologo",
  "Cardiologo pediatra",
  "Carniceria",
  "Carpinteria",
  "Carpintero",
  "Carrusel",
  "Casa de empenos",
  "Casa de juegos de apuestas",
  "Casa de subastas",
  "Casa de subastas de ganado",
  "Casa de vacaciones para no fumadores",
  "Casa encantada",
  "Casa rural",
  "Casino",
  "Castillo",
  "Catastro",
  "Catedral",
  "Cementerio",
  "Cementerio de mascotas",
  "Cementerio militar",
  "Central electrica",
  "Central nuclear",
  "Central telefonica",
  "Centro acuatico",
  "Centro artistico",
  "Centro asistencial de dia",
  "Centro civico",
  "Centro comercial",
  "Centro comercial outlet",
  "Centro comunitario",
  "Centro cultural",
  "Centro de acogida",
  "Centro de acogida de mujeres",
  "Centro de acogida para personas sin hogar",
  "Centro de adelgazamiento",
  "Centro de aprendizaje",
  "Centro de aprendizaje a distancia",
  "Centro de ayuda para embarazadas",
  "Centro de bienestar social",
  "Centro de bronceado",
  "Centro de buceo",
  "Centro de caida libre",
  "Centro de comercio y exhibiciones",
  "Centro de depilacion laser",
  "Centro de deportes de aventura",
  "Centro de detencion de menores",
  "Centro de diagnostico",
  "Centro de diagnostico por imagen",
  "Centro de dialisis",
  "Centro de educacion especial",
  "Centro de educacion preescolar",
  "Centro de educacion secundaria",
  "Centro de empleo",
  "Centro de entrenamiento de beisbol",
  "Centro de esqui cubierto",
  "Centro de estetica",
  "Centro de estudios",
  "Centro de examen fisico",
  "Centro de exposicion de articulos para el hogar",
  "Centro de formacion",
  "Centro de formacion profesional",
  "Centro de informacion turistica",
  "Centro de Internamiento de Extranjeros",
  "Centro de jardineria",
  "Centro de la tercera edad",
  "Centro de laser tag",
  "Centro de llamadas",
  "Centro de meditacion",
  "Centro de negocios",
  "Centro de ocio",
  "Centro de ocio infantil",
  "Centro de oftalmologia",
  "Centro de paintball",
  "Centro de pilates",
  "Centro de planificacion familiar",
  "Centro de reciclaje",
  "Centro de reciclaje de latas y botellas",
  "Centro de recreo",
  "Centro de refuerzo escolar",
  "Centro de rehabilitacion",
  "Centro de reparacion de trenes",
  "Centro de resonancias magneticas",
  "Centro de retiro",
  "Centro de retiro de yoga",
  "Centro de salas de escape",
  "Centro de salud",
  "Centro de salud comunitario",
  "Centro de salud infantil",
  "Centro de salud y bienestar",
  "Centro de seguridad vial",
  "Centro de spa",
  "Centro de tratamiento de trastornos alimentarios",
  "Centro de tratamiento por maltrato domestico",
  "Centro de visitantes",
  "Centro de yoga",
  "Centro deportivo",
  "Centro educativo",
  "Centro escolar",
  "Centro espiritual",
  "Centro Head Start",
  "Centro juvenil",
  "Centro medico",
  "Centro oncologico",
  "Centro para el tratamiento de la diabetes",
  "Centro para exploradores",
  "Centro para veteranos",
  "Centro para victimas de crimenes",
  "Centro penitenciario",
  "Centros de formacion para obtener el carne de conducir",
  "Cereria",
  "Cerrajero",
  "Cerveceria",
  "Cerveceria al aire libre",
  "Cerveceria artesanal",
  "Chapisteria",
  "Chatarreria",
  "Chatarrero",
  "Chiringuito",
  "Chocolateria",
  "Churreria",
  "Ciber",
  "Cibercafe",
  "Ciclismo en carretera",
  "Cine",
  "Cine al aire libre",
  "Cine Imax",
  "Circo",
  "Circuito de BMX",
  "Circuito de carreras",
  "Circuito de karts",
  "Cirujano",
  "Cirujano especialista en LASIK",
  "Cirujano especialista en manos",
  "Cirujano gastrointestinal",
  "Cirujano maxilofacial",
  "Cirujano ortopedico",
  "Cirujano plastico",
  "Cirujano vascular",
  "Ciudad fantasma",
  "Ciudad termal",
  "Clase de fitness",
  "Clase de preparacion para el parto",
  "Clases de salsa",
  "Clinica ambulatoria",
  "Clinica andrologica",
  "Clinica china",
  "Clinica de acupuntura",
  "Clinica de atencion sin cita previa",
  "Clinica de cirugia plastica",
  "Clinica de fisioterapia",
  "Clinica de interrupcion del embarazo",
  "Clinica de medicina deportiva",
  "Clinica de oftalmologia",
  "Clinica de otorrinolaringologia",
  "Clinica de psicopedagogia",
  "Clinica de reproduccion asistida",
  "Clinica de salud reproductiva",
  "Clinica de trasplante capilar",
  "Clinica del dolor",
  "Clinica del sueno",
  "Clinica dental",
  "Clinica dermatologica",
  "Clinica especializada",
  "Clinica ginecologica",
  "Clinica gratuita",
  "Clinica ortopedica",
  "Clinica para viajeros",
  "Clinica psiquiatrica",
  "Club",
  "Club automovilistico",
  "Club de aikido",
  "Club de ajedrez",
  "Club de ajedrez y cartas",
  "Club de anfitriones",
  "Club de anime",
  "Club de artes marciales",
  "Club de badminton",
  "Club de baile",
  "Club de baloncesto",
  "Club de balonmano",
  "Club de beisbol",
  "Club de billar",
  "Club de blues",
  "Club de bolos",
  "Club de bolos sobre hierba",
  "Club de boxeo",
  "Club de bridge",
  "Club de buceo",
  "Club de cabare",
  "Club de campo",
  "Club de canoas y kayak",
  "Club de carnaval",
  "Club de caza",
  "Club de ciclismo",
  "Club de comedia",
  "Club de criquet",
  "Club de croquet",
  "Club de curlin",
  "Club de entretenimiento para adultos",
  "Club de esqui",
  "Club de esqui acuatico",
  "Club de excombatientes",
  "Club de futbol",
  "Club de golf",
  "Club de hockey",
  "Club de hockey sobre hielo",
  "Club de jazz",
  "Club de judo",
  "Club de karaoke",
  "Club de la liga de rugby",
  "Club de modelos a escala",
  "Club de musica rock",
  "Club de natacion",
  "Club de padel",
  "Club de patinaje sobre hielo",
  "Club de patinaje sobre ruedas",
  "Club de pesca",
  "Club de ponis",
  "Club de raquetbol",
  "Club de remo",
  "Club de rugby",
  "Club de salvamento de surf",
  "Club de sauna",
  "Club de softbol",
  "Club de squash",
  "Club de tenis",
  "Club de tenis de mesa",
  "Club de tiradores",
  "Club de tiro",
  "Club de tiro con arco",
  "Club de trabajadores",
  "Club de trajes tradicionales",
  "Club de vela",
  "Club de voleibol",
  "Club de voley-playa",
  "Club deportivo",
  "Club ecuestre",
  "Club nautico",
  "Club nocturno",
  "Club nudista",
  "Club social",
  "Cobro de deudas",
  "Cocteleria",
  "Colchoneria",
  "Colegio bilingue",
  "Colegio concertado",
  "Colegio electoral",
  "Colegio mayor",
  "Colegio Oficial de Abogados",
  "Colegio privado",
  "Colegio publico",
  "Colegio religioso",
  "Comadrona",
  "Comedor escolar",
  "Comedor social",
  "Comerciante de arte",
  "Comerciante de motos de nieve",
  "Comerciante de oro",
  "Comercio",
  "Comic cafe",
  "Comida a domicilio",
  "Comida china para llevar",
  "Compania aerea",
  "Compania de danza",
  "Compania de opera",
  "Compania de seguros",
  "Compania de seguros medicos",
  "Compania de teatro",
  "Compania del gas",
  "Compania electrica",
  "Compania farmaceutica",
  "Compania suministradora de agua",
  "Compania telefonica",
  "Competicion de natacion",
  "Complejo de apartamentos",
  "Complejo de viviendas",
  "Complejo hotelero",
  "Complejo turistico en la playa",
  "Comprador de diamantes",
  "Comprador de joyas",
  "Compraventa de automoviles",
  "Compraventa de yates",
  "Comunidad para jubilados",
  "Concesionario Acura",
  "Concesionario Audi",
  "Concesionario BMW",
  "Concesionario Buick",
  "Concesionario Cadillac",
  "Concesionario Chevrolet",
  "Concesionario Chrysler",
  "Concesionario Citroen",
  "Concesionario de autocaravanas",
  "Concesionario de automoviles",
  "Concesionario de camiones",
  "Concesionario de camiones de segunda mano",
  "Concesionario de carros de golf",
  "Concesionario de ciclomotores",
  "Concesionario de coches de carreras",
  "Concesionario de escuteres",
  "Concesionario de gruas",
  "Concesionario de motocicletas BMW",
  "Concesionario de motocicletas Kawasaki",
  "Concesionario de motocicletas Suzuki",
  "Concesionario de motocicletas Triumph",
  "Concesionario de motocicletas Yamaha",
  "Concesionario de motos",
  "Concesionario de remolque de embarcaciones",
  "Concesionario de remolques",
  "Concesionario de remolques de servicios publicos",
  "Concesionario de tractores",
  "Concesionario de vehiculos todoterreno",
  "Concesionario Dodge",
  "Concesionario Ducati",
  "Concesionario Fiat",
  "Concesionario Ford",
  "Concesionario GMC",
  "Concesionario Harley-Davidson",
  "Concesionario Honda",
  "Concesionario Hyundai",
  "Concesionario Infiniti",
  "Concesionario Isuzu",
  "Concesionario Jaguar",
  "Concesionario Jeep",
  "Concesionario Kia",
  "Concesionario Land Rover",
  "Concesionario Lexus",
  "Concesionario Lincoln Mercury",
  "Concesionario Mazda",
  "Concesionario Mercedes Benz",
  "Concesionario MINI",
  "Concesionario Mitsubishi",
  "Concesionario Nissan",
  "Concesionario Oldsmobile",
  "Concesionario Peugeot",
  "Concesionario Pontiac",
  "Concesionario Porsche",
  "Concesionario Renault",
  "Concesionario Saab",
  "Concesionario Saturn",
  "Concesionario Seat",
  "Concesionario Skoda",
  "Concesionario Smart",
  "Concesionario Subaru",
  "Concesionario Suzuki",
  "Concesionario Toyota",
  "Concesionario Volkswagen",
  "Concesionario Volvo",
  "Condominio",
  "Congregacion",
  "Consejeria de Educacion",
  "Consejero familiar",
  "Consejero matrimonial",
  "Consejo comarcal",
  "Conservacion del patrimonio",
  "Conservatorio de danza",
  "Conservatorio de musica",
  "Construccion de maquinaria",
  "Construccion naval",
  "Constructor",
  "Constructor de aparcamientos techados y pergolas",
  "Constructor de campos de golf",
  "Constructor de casas modulares",
  "Constructor de casas personalizadas",
  "Constructor de cenadores",
  "Constructor de cobertizos",
  "Constructor de garajes",
  "Constructor de mausoleos",
  "Constructor de muelles",
  "Constructor de plataformas y terrazas",
  "Consulado extranjero",
  "Consultor inmobiliario",
  "Consultora de administracion empresarial",
  "Consultora de marketing",
  "Consultora financiera",
  "Consultora informatica",
  "Consultora medioambiental",
  "Consultoria de recursos humanos",
  "Contable",
  "Contratista",
  "Contratista de acabado de interiores",
  "Contratista de aire acondicionado",
  "Contratista de alambradas",
  "Contratista de albanileria",
  "Contratista de barandillas",
  "Contratista de demolicion",
  "Contratista de estanques",
  "Contratista de estuco",
  "Contratista de excavacion",
  "Contratista de explotacion forestal",
  "Contratista de ferrocarril",
  "Contratista de fuentes",
  "Contratista de mamposteria sin mortero",
  "Contratista de materiales para suelos",
  "Contratista de pavimentacion",
  "Contratista de perforacion",
  "Contratista de perforacion de pozos",
  "Contratista de piscinas",
  "Contratista de pistas de baloncesto",
  "Contratista de revestimientos",
  "Contratista de servicios publicos",
  "Contratista de sistemas de aspersores para jardin",
  "Contratista de solarios",
  "Contratista de telecomunicaciones",
  "Contratista de tragaluces",
  "Contratista general",
  "Contratista mecanico",
  "Convento",
  "Conversion a GLP",
  "Cooperativa agropecuaria",
  "Cooperativa de aceite de oliva",
  "Cooperativa de ahorro y credito",
  "Cooperativa de credito federal",
  "Cooperativa de viviendas",
  "Copisteria",
  "Coro",
  "Corredor de bolsa",
  "Corredor de seguros",
  "Corredor hipotecario",
  "Creperia",
  "Criador canino",
  "Criador de caballos",
  "Cristalero",
  "Cuadrilatero de boxeo",
  "Cuarteles militares",
  "Cuarto de herramientas",
  "Cuchilleria",
  "Cuidado de los pies",
  "Cuidador de mascotas",
  "Cura de los huesos",
  "Curtiduria",
  "Defensa civil",
  "Delegacion de Servicios Sociales",
  "Delegacion regional del gobierno",
  "Delicatessen",
  "Delicatessen de carniceria",
  "Delicatessen japonesa",
  "Dentista",
  "Dentista cosmetico",
  "Departamento de asuntos de veteranos",
  "Departamento de Finanzas de la Seguridad Social",
  "Departamento de obras publicas",
  "Departamento de Ocupacion del Estado",
  "Departamento de planificacion urbanistica",
  "Departamento de salud publica",
  "Departamento de Seguridad Publica",
  "Departamento de Transporte",
  "Departamento del sheriff",
  "Departamento fiscal",
  "Departamento local de ocupacion",
  "Departamento local de transporte",
  "Departamento municipal de turismo",
  "Departamento universitario",
  "Depilacion con cera",
  "Deportes de aventura",
  "Deposito de automoviles",
  "Dermatologo",
  "Desarrollo de productos e investigacion",
  "Desarrollo mercantil",
  "Desguace",
  "Deshollinador",
  "Destileria de sake",
  "Destileria de shochu",
  "Destino religioso",
  "Detective privado",
  "Diner",
  "Diputacion",
  "Diputacion provincial",
  "Dique",
  "Discoteca",
  "Disenador de iluminacion de paisajismo",
  "Disenador de joyas",
  "Disenador de sitios web",
  "Disenador grafico",
  "Distribucion de tierras",
  "Distribuidor de acero",
  "Distribuidor de casas modulares",
  "Distribuidor de cerveza",
  "Distribuidor de comestibles",
  "Distribuidor de diamantes",
  "Distribuidor de equipos de telecomunicacion",
  "Distribuidor de equipos para excursiones en balsa",
  "Distribuidor de maquinas expendedoras automaticas",
  "Distribuidor de maquinas fotocopiadoras",
  "Distribuidor de maquinas recreativas",
  "Distribuidor de motores diesel",
  "Distribuidor de Opel",
  "Distribuidor de papel",
  "Distribuidor de remolques para caballos",
  "Distribuidores de carretillas elevadoras",
  "DJ",
  "Ebanista",
  "Edificio de apartamentos",
  "Edificio de apartamentos amueblados",
  "Editor",
  "Editor de periodicos",
  "Editorial",
  "Editorial de musica impresa",
  "Educacion mixta",
  "Electricista",
  "Electrodomesticos para mayoristas",
  "Embajada",
  "Emisora de radio",
  "Empresa constructora",
  "Empresa de acabados metalicos",
  "Empresa de administracion de propiedades",
  "Empresa de aguas minerales",
  "Empresa de aislamientos",
  "Empresa de alojamiento web",
  "Empresa de aridos",
  "Empresa de armaduras y ferrallas",
  "Empresa de asfaltado",
  "Empresa de autobuses",
  "Empresa de azulejos y pavimentos ceramicos",
  "Empresa de biotecnologia",
  "Empresa de calefaccion",
  "Empresa de climatizacion",
  "Empresa de construccion",
  "Empresa de construccion de carreteras",
  "Empresa de construccion de pistas de tenis",
  "Empresa de contabilidad",
  "Empresa de embalaje",
  "Empresa de embotellado de aceite de oliva",
  "Empresa de escayolas",
  "Empresa de fabricacion de plastico",
  "Empresa de fumigacion y control de plagas",
  "Empresa de hierros y aceros",
  "Empresa de hormigonado",
  "Empresa de importacion y exportacion",
  "Empresa de instalacion de cubiertas",
  "Empresa de instalacion de escaleras",
  "Empresa de instalacion de television por cable",
  "Empresa de mantenimiento de aeronaves",
  "Empresa de marmoles",
  "Empresa de medios de comunicacion",
  "Empresa de mensajeria",
  "Empresa de moldeo por inyeccion de plastico",
  "Empresa de montaje de estands para ferias",
  "Empresa de organizacion de eventos",
  "Empresa de petroleo y gas natural",
  "Empresa de pulidos metalicos",
  "Empresa de recogida de escombros",
  "Empresa de relaciones publicas",
  "Empresa de software",
  "Empresa de suministros industriales",
  "Empresa de topografia",
  "Empresa de trabajo temporal",
  "Empresa de transporte por camion",
  "Empresa de tratamiento del agua",
  "Empresa de trenes del area metropolitana",
  "Empresa ferroviaria",
  "Empresa minera",
  "Empresa portuaria",
  "Empresa suministradora de gas butano",
  "Encargado de contratacion",
  "Endocrinologo",
  "Endodoncista",
  "Entrenador de caballos",
  "Entrenador de mascotas",
  "Entrenador personal",
  "Envasador de carnes",
  "Envase de alimentos basicos",
  "Equipo de procesamiento de alimentos",
  "Equipo para mineria",
  "Equipos para panaderias",
  "Equipos y soluciones de energia",
  "Escalada",
  "Escenario",
  "Escuela",
  "Escuela",
  "Escuela catolica",
  "Escuela checa",
  "Escuela comunitaria",
  "Escuela de acupuntura",
  "Escuela de administracion",
  "Escuela de aerodanza",
  "Escuela de agentes inmobiliarios",
  "Escuela de aikido",
  "Escuela de aromaterapia",
  "Escuela de Arquitectura",
  "Escuela de arte",
  "Escuela de arte dramatico",
  "Escuela de artes marciales",
  "Escuela de ballet",
  "Escuela de boxeo",
  "Escuela de cocina",
  "Escuela de comercio",
  "Escuela de contabilidad",
  "Escuela de defensa personal",
  "Escuela de diseno de moda",
  "Escuela de educacion para adultos",
  "Escuela de enfermeria",
  "Escuela de equitacion",
  "Escuela de esgrima",
  "Escuela de esqui",
  "Escuela de estudios superiores de posgrado",
  "Escuela de flamenco",
  "Escuela de formacion para emergencias",
  "Escuela de hosteleria",
  "Escuela de Jiu-jitsu",
  "Escuela de judo",
  "Escuela de karate",
  "Escuela de kickboxing",
  "Escuela de kung-fu",
  "Escuela de lucha libre",
  "Escuela de masajistas",
  "Escuela de musica",
  "Escuela de natacion",
  "Escuela de negocios",
  "Escuela de peluqueria",
  "Escuela de primaria",
  "Escuela de samba",
  "Escuela de surf",
  "Escuela de taekwondo",
  "Escuela de taichi",
  "Escuela de telecomunicaciones",
  "Escuela de vela",
  "Escuela de vuelo",
  "Escuela de wing chun",
  "Escuela deportiva",
  "Escuela Montessori",
  "Escuela para sordos",
  "Escuela parroquial",
  "Escuela preparatoria",
  "Escuela primaria",
  "Escuela secundaria superior",
  "Escuela tecnica",
  "Escuela universitaria",
  "Escultura",
  "Espacio de coworking",
  "Especialista en diabetes",
  "Especialista en enfermedades infecciosas",
  "Especialista en fertilidad",
  "Especialista en medicina holistica",
  "Establecimiento de comida preparada",
  "Establecimiento de deposito y venta",
  "Establecimiento de jamon serrano",
  "Establecimiento de reparacion de articulos electronicos",
  "Establecimiento de sopas",
  "Establecimiento de tofu",
  "Establecimiento de venta de madera",
  "Establo",
  "Establo para caballos",
  "Estacion de carga de vehiculos electricos",
  "Estacion de clasificacion",
  "Estacion de esqui",
  "Estacion de guardacostas",
  "Estacion de inspeccion de humos",
  "Estacion de inspeccion de vehiculos",
  "Estacion de pesaje",
  "Estacionamiento de autocaravanas",
  "Estadio",
  "Estancia en granjas",
  "Estanco",
  "Estanque de pesca",
  "Esteticista facial",
  "Estilista",
  "Estudio de arquitectura",
  "Estudio de arquitectura paisajistica",
  "Estudio de Bikram Yoga",
  "Estudio de books para modelos",
  "Estudio de fotografia",
  "Estudio de grabacion",
  "Estudio de pintura artistica",
  "Estudio de retratos",
  "Estudio de tatuajes",
  "Estudio de vidrio",
  "Evento de tiro con arco",
  "Excursiones de pesca",
  "Explotacion acuicola",
  "Explotacion lechera",
  "Exposicion",
  "Fabrica",
  "Fabrica de automoviles",
  "Fabrica de azucar",
  "Fabrica de bolsas de papel",
  "Fabrica de bolsas de plastico",
  "Fabrica de cerveza",
  "Fabrica de chocolate",
  "Fabrica de conservas",
  "Fabrica de maquinaria",
  "Fabrica de maquinaria agricola",
  "Fabrica de material electrico",
  "Fabrica de muebles",
  "Fabrica de papel",
  "Fabrica de puertas",
  "Fabrica de zapatos",
  "Fabricante / distribuidor de estatuas",
  "Fabricante de acero",
  "Fabricante de alimentos",
  "Fabricante de alimentos congelados",
  "Fabricante de articulos electronicos",
  "Fabricante de casas de madera",
  "Fabricante de ceramica",
  "Fabricante de cestas de mimbre",
  "Fabricante de condimentos de alimentos",
  "Fabricante de edificios portatiles",
  "Fabricante de herramientas",
  "Fabricante de pianos",
  "Fabricante de puestos de exhibicion",
  "Fabricante de remolques",
  "Fabricante de repuestos para automoviles",
  "Fabricante de repuestos para maquinaria",
  "Fabricante de ropa de deporte",
  "Fabricante de tecnologia medica",
  "Fabricante de velas para embarcaciones",
  "Fabricante de vigas",
  "Facultad de Bellas Artes",
  "Facultad de Ciencias de la Actividad Fisica y del Deporte",
  "Facultad de Derecho",
  "Facultad de derecho",
  "Facultad de Geografia e Historia",
  "Facultad de medicina",
  "Facultad de Medios y Ciencias de la Informacion",
  "Facultad de odontologia",
  "Facultad de Psicologia",
  "Facultad de quimica",
  "Facultad Politecnica",
  "Farmacia",
  "Farmacia homeopatica",
  "Farmacia veterinaria",
  "Favela",
  "Feria artesanal",
  "Ferreteria",
  "Festival",
  "Fiscal de distrito",
  "Fiscalia publica",
  "Fisiatra",
  "Fisioterapeuta",
  "Floristeria",
  "Floristeria mayorista",
  "Fontanero",
  "Formacion en emergencias",
  "Fortaleza",
  "Fotografo",
  "Fotografo aereo",
  "Fotografo de bodas",
  "Fruteria",
  "Fuente de agua potable",
  "Fuerza Maritima de Autodefensa",
  "Funcionario ejecutivo del tribunal",
  "Fundacion",
  "Fundacion de investigacion",
  "Fundicion",
  "Funeraria",
  "Galeria de arte",
  "Galeria de arte aborigen",
  "Ganadero",
  "Gasolinera",
  "Gasolinera alternativa",
  "Gastroenterologo",
  "Genealogista",
  "Gestion de divorcios",
  "Gestor",
  "Gestoria",
  "Gimnasio",
  "Gimnasio",
  "Gimnasio con rocodromo",
  "Gimnasio de boxeo Muay Thai",
  "Ginecologo",
  "Grabado de piedra",
  "Grabador",
  "Grabador de joyas",
  "Gran superficie",
  "Grandes almacenes",
  "Granja",
  "Granja avicola",
  "Granja eolica",
  "Granja escuela",
  "Granja organica",
  "Gravera",
  "Gremio",
  "Grupo de artes escenicas",
  "Grupo medico",
  "Guarderia",
  "Guarderia canina",
  "Guarderia familiar",
  "Guarderia para gatos",
  "Guardia Civil",
  "Guardia Di Finanza",
  "Gurudwara",
  "Hacienda turistica",
  "Hamburgueseria",
  "Heladeria",
  "Helipuerto",
  "Hematologo",
  "Herbolario",
  "Herrero",
  "Higienista dental",
  "Hilanderia de algodon",
  "Hipermercado",
  "Homeopata",
  "Hospital",
  "Hospital cardiovascular",
  "Hospital de maternidad",
  "Hospital especializado",
  "Hospital general",
  "Hospital gubernamental",
  "Hospital infantil",
  "Hospital militar",
  "Hospital para veteranos",
  "Hospital privado",
  "Hospital psiquiatrico",
  "Hospital universitario",
  "Hospital veterinario",
  "Hostel para gatos",
  "Hotel",
  "Hotel boutique",
  "Hotel capsula",
  "Hotel con fuente termal",
  "Hotel de conferencias",
  "Hotel de larga estancia",
  "Hotel de lujo",
  "Hotel economico",
  "Hotel familiar",
  "Hotel japones con fuente termal",
  "Hotel japones economico",
  "Hotel para encuentros amorosos",
  "Hoteles japoneses",
  "Huerto",
  "Huerto de calabazas",
  "Iglesia",
  "Iglesia adventista del septimo dia",
  "Iglesia anglicana",
  "Iglesia apostolica",
  "Iglesia armenia",
  "Iglesia bautista",
  "Iglesia Calvary Chapel",
  "Iglesia catolica",
  "Iglesia coreana",
  "Iglesia cristiana",
  "Iglesia cuaquera",
  "Iglesia de Jesucristo",
  "Iglesia de Jesucristo de los Santos de los Ultimos Dias",
  "Iglesia de la Alianza",
  "Iglesia de la Unidad",
  "Iglesia de la Vina",
  "Iglesia de las Asambleas de Dios",
  "Iglesia de los Discipulos de Cristo",
  "Iglesia de los testigos de Jehova",
  "Iglesia del Evangelio",
  "Iglesia del Evangelio Cuadrangular",
  "Iglesia del Nazareno",
  "Iglesia del Pleno Evangelio",
  "Iglesia episcopal",
  "Iglesia evangelica",
  "Iglesia Friends Church",
  "Iglesia hispana",
  "Iglesia luterana",
  "Iglesia menonita",
  "Iglesia metodista",
  "Iglesia Metodista Unida",
  "Iglesia morava",
  "Iglesia New Age",
  "Iglesia no vinculada a una denominacion religiosa",
  "Iglesia ortodoxa",
  "Iglesia ortodoxa griega",
  "Iglesia ortodoxa oriental",
  "Iglesia ortodoxa rusa",
  "Iglesia para sordos",
  "Iglesia pentecostal",
  "Iglesia presbiteriana",
  "Iglesia protestante",
  "Iglesia reformista",
  "Iglesia Unida de Canada",
  "Iglesia Unida de Cristo",
  "Iglesia Unitaria Universalista",
  "Iglesia Vida Abundante",
  "Iglesia Wesleyana",
  "Importador",
  "Imprenta",
  "Imprenta comercial",
  "Impresora de etiquetas personalizadas",
  "Impresora digital",
  "Industria de cosmeticos",
  "Industria naviera",
  "Ingeniero",
  "Ingeniero aeronautico",
  "Ingeniero agronomo",
  "Ingeniero civil",
  "Ingeniero de minas",
  "Ingeniero de telecomunicaciones",
  "Ingeniero electrico",
  "Ingeniero en residuos solidos",
  "Ingeniero estructural",
  "Ingeniero industrial",
  "Ingeniero mecanico",
  "Ingeniero medioambiental",
  "Inmunologo",
  "Inspeccion sanitaria",
  "Inspeccion tecnica de vehiculos",
  "Inspector de bienes inmuebles comerciales",
  "Inspector de construccion",
  "Inspector de vivienda",
  "Instalacion de almacenamiento de autocaravanas",
  "Instalacion de almacenamiento de botellas de vino",
  "Instalacion de almacenamiento de embarcaciones",
  "Instalacion de almacenamiento en frio",
  "Instalador de gas",
  "Instalador de moquetas",
  "Institucion educativa",
  "Institucion financiera",
  "Institucion religiosa",
  "Instituto de formacion en aviacion",
  "Instituto de Geografia y Estadistica",
  "Instituto de investigacion",
  "Instituto de Reforma Agraria",
  "Instituto de secundaria",
  "Instituto femenino",
  "Instituto para ninos",
  "Interiorista",
  "Internista",
  "Invernadero",
  "Investigador de mercado",
  "Investigador privado",
  "Jamoneria",
  "Jardin",
  "Jardin botanico",
  "Jardin comunitario",
  "Jardin con balneario",
  "Jardin de infancia",
  "Jardin de infancia Waldorf",
  "Jardinero",
  "Jefatura de trafico",
  "Joyeria",
  "Joyeria mayorista",
  "Juez de distrito",
  "Jugueteria",
  "Junta militar",
  "Junta municipal de distrito",
  "Juzgados municipales",
  "Karaoke",
  "Kinesiologo",
  "Kiosco",
  "Laboratorio",
  "Laboratorio de analisis clinicos",
  "Laboratorio de radiografias",
  "Laboratorio dental",
  "Laboratorio farmaceutico",
  "Laboratorio fotografico",
  "Laboratorio quimico",
  "Lago para natacion",
  "Lapidario",
  "Lavanderia",
  "Lavanderia de autoservicio",
  "Libreria",
  "Libreria anticuaria",
  "Libreria cristiana",
  "Libreria especializada en derecho",
  "Libreria infantil",
  "Libreria religiosa",
  "Liquidador",
  "Liquidador de bienes inmuebles",
  "Local de ambiente",
  "Locutorio",
  "Logopeda",
  "Lonja de pescado",
  "Lounge",
  "Lucha libre",
  "Ludoteca",
  "Lugar de culto",
  "Lugar de interes historico",
  "Lugar de peregrinacion",
  "Mago",
  "Maquina expendedora de cafe",
  "Maquina expendedora de productos de cosmetica",
  "Maquina expendedora de productos de cuidado para la piel",
  "Maquina expendedora de productos electronicos",
  "Marae",
  "Marisqueria",
  "Marroquineria",
  "Masaje erotico",
  "Masajista",
  "Masajista deportivo",
  "Masajista tailandes",
  "Matadero",
  "Mayorista",
  "Mayorista de aparatos electricos",
  "Mayorista de arroz",
  "Mayorista de articulos de cristal",
  "Mayorista de articulos para la higiene",
  "Mayorista de cafe",
  "Mayorista de carnes",
  "Mayorista de confiteria",
  "Mayorista de cuentas",
  "Mayorista de frutas",
  "Mayorista de frutas y hortalizas",
  "Mayorista de lenceria",
  "Mayorista de marisco",
  "Mayorista de muebles",
  "Mayorista e importador de vino",
  "Mayorista textil",
  "Mecanico protesico dental",
  "Medico",
  "Medico de familia",
  "Medico de medicina general",
  "Medico de urgencias",
  "Medico especializado en el tratamiento del dolor",
  "Medico especializado en medicina deportiva",
  "Medico especializado en medicina laboral",
  "Medico forense",
  "Mercadillo",
  "Mercado",
  "Mercado de alimentos frescos",
  "Mercado de flores",
  "Mercado de productos agricolas",
  "Mercado de productos del campo",
  "Mercado de qing fang",
  "Mercado de te",
  "Mercado flotante",
  "Mercado ganadero",
  "Mercado Hua Niao",
  "Mercado mayorista de ropa",
  "Mercado mayorista de verduras",
  "Mercado nocturno",
  "Merceria",
  "Meson",
  "Mezquita",
  "Mina",
  "Ministerio de Educacion",
  "Mirador",
  "Mision",
  "Modista",
  "Molino",
  "Molino de agua",
  "Molino de arroz",
  "Molino de harina",
  "Monasterio",
  "Monopolio minorista de alcohol",
  "Montana rusa",
  "Morgue",
  "Motel",
  "Muelle de pesca",
  "Museo",
  "Museo al aire libre",
  "Museo arqueologico",
  "Museo belico",
  "Museo de arte",
  "Museo de arte moderno",
  "Museo de artesania",
  "Museo de cera",
  "Museo de ciencias",
  "Museo de escultura",
  "Museo de historia",
  "Museo de historia del espacio",
  "Museo de historia local",
  "Museo de historia natural",
  "Museo de zoologia",
  "Museo del ferrocarril",
  "Museo del juguete",
  "Museo etnografico",
  "Museo infantil",
  "Museo maritimo",
  "Museo militar",
  "Museo nacional",
  "Museo patrimonial",
  "Museo tecnologico",
  "Naturopata",
  "Nefrologo",
  "Neonatologo",
  "Neumologo",
  "Neurocirujano",
  "Neurologo",
  "Noria",
  "Notaria",
  "Numismatico",
  "Nutricionista",
  "Observatorio",
  "Odontologo pediatra",
  "Oficina de abogado defensor de oficio",
  "Oficina de administracion municipal",
  "Oficina de administracion tributaria",
  "Oficina de aduanas",
  "Oficina de aduanas principal",
  "Oficina de arquitectura de interiores",
  "Oficina de Asuntos Juridicos",
  "Oficina de Asuntos Tribales",
  "Oficina de atencion al ciudadano",
  "Oficina de cambio de divisas",
  "Oficina de correos",
  "Oficina de empleo",
  "Oficina de estudio topografico",
  "Oficina de gobierno local",
  "Oficina de la Administracion",
  "Oficina de la prefectura japonesa",
  "Oficina de la Seguridad Social",
  "Oficina de libertad condicional",
  "Oficina de licencias",
  "Oficina de medio ambiente",
  "Oficina de pasaportes",
  "Oficina de patentes",
  "Oficina de reclutamiento militar",
  "Oficina de registro",
  "Oficina de seguridad publica",
  "Oficina de trafico",
  "Oficina de visados y pasaportes",
  "Oficina del censo electoral",
  "Oficina del distrito escolar",
  "Oficina del Gobierno",
  "Oficina del Gobierno del Distrito",
  "Oficina del gobierno federal",
  "Oficina estatal de educacion",
  "Oficina medica",
  "Oficina tributaria municipal",
  "Oficinas de administracion del condado",
  "Oficinas de empresa",
  "Oficinas del ayuntamiento",
  "Oftalmologo",
  "Oftalmologo pediatra",
  "Oncologo",
  "Opera",
  "Optica",
  "Optometrista",
  "Orfanato",
  "Orfebre (cobre)",
  "Orfebre (oro)",
  "Organizacion agricola",
  "Organizacion de aborigenes e islenos del estrecho de Torres",
  "Organizacion de arte",
  "Organizacion de ayuda y servicios para discapacitados",
  "Organizacion de gays y lesbianas",
  "Organizacion de servicios sociales",
  "Organizacion de tiendas 24 horas",
  "Organizacion de voluntariado",
  "Organizacion femenina",
  "Organizacion juvenil",
  "Organizacion maori",
  "Organizacion no gubernamental",
  "Organizacion religiosa",
  "Organizacion sin animo de lucro",
  "Organizador de bodas",
  "Organizador de eventos",
  "Organizador profesional",
  "Orquesta",
  "Orquideario",
  "Ortodoncista",
  "Osteopata",
  "Otorrinolaringologo",
  "Outlet",
  "Pabellon de baile",
  "Pabellon para playa",
  "Pagoda",
  "Paisajista",
  "Pajareria",
  "Palacio de congresos",
  "Palacio de exposiciones y congresos",
  "Panaderia",
  "Panaderia mayorista",
  "Papeleria",
  "Parada de taxis",
  "Parada para camiones",
  "Parque",
  "Parque acuatico",
  "Parque de animales",
  "Parque de animales salvajes y safari",
  "Parque de atracciones",
  "Parque de BMX",
  "Parque de bomberos",
  "Parque de ciclismo",
  "Parque deportivo",
  "Parque ecologico",
  "Parque empresarial",
  "Parque estatal",
  "Parque infantil",
  "Parque infantil cubierto",
  "Parque local",
  "Parque nacional",
  "Parque para perros",
  "Parque tecnologico",
  "Parque tematico",
  "Parrilla",
  "Parroquia",
  "Partido politico",
  "Paseador de perros",
  "Pasteleria",
  "Pasteleria especializada en tartas nupciales",
  "Pasteleria francesa",
  "Patologo",
  "Patrulla fronteriza",
  "Peaje",
  "Pediatra",
  "Pediluvio",
  "Peletero mayorista",
  "Peluqueria",
  "Peluquero a domicilio",
  "Peluquero de mascotas",
  "Peluquero especialista en extensiones",
  "Pension",
  "Perfumeria",
  "Periodoncista",
  "Periodoncista de implantes dentales",
  "Perrera",
  "Persona de mantenimiento",
  "Pescaderia",
  "Picadero",
  "Piercing de orejas",
  "Pintor",
  "Pintura",
  "Piscifactoria",
  "Piscina",
  "Piscina cubierta",
  "Piscina de salto acrobatico",
  "Piscina de waterpolo",
  "Piscina publica",
  "Piscinas",
  "Pista de aterrizaje",
  "Pista de atletismo",
  "Pista de badminton",
  "Pista de balonmano",
  "Pista de carreras",
  "Pista de carreras off-road",
  "Pista de hockey",
  "Pista de padel",
  "Pista de patinaje sobre hielo",
  "Pista de patinaje sobre ruedas",
  "Pista de squash",
  "Pista de tenis",
  "Pizza para llevar",
  "Pizzeria",
  "Pizzeria a domicilio",
  "Planetario",
  "Planta de desalinizacion",
  "Planta de energia solar fotovoltaica",
  "Planta de grava",
  "Planta de refrigeracion",
  "Planta de tratamiento de aguas",
  "Planta de tratamiento de aguas residuales",
  "Planta de tratamiento de arena",
  "Planta depuradora",
  "Planta incineradora",
  "Planta quimica",
  "Plaza de toros",
  "Podologo",
  "Policia civil",
  "Policia Federal",
  "Policia nacional",
  "Polideportivo",
  "Poligono industrial",
  "Polleria",
  "Portabicicletas",
  "Posada",
  "Practica de futbol",
  "Prestamista hipotecario",
  "Procesamiento de fotos para pasaporte",
  "Procesamiento de frutas y verduras",
  "Procesamiento del pescado",
  "Proctologo",
  "Producteur de Champagne",
  "Producteur de Foie Gras",
  "Productor de gomaespuma",
  "Productor discografico",
  "Productora de teatro",
  "Productora discografica",
  "Profesional de los globos",
  "Profesional de medicina alternativa",
  "Profesor de bailes de salon",
  "Profesor de buceo",
  "Profesor de esqui acuatico",
  "Profesor de golf",
  "Profesor de guitarra",
  "Profesor de juegos de azar y apuestas",
  "Profesor de musica",
  "Profesor de natacion",
  "Profesor de navegacion",
  "Profesor de piano",
  "Profesor de tenis",
  "Programa de acondicionamiento fisico",
  "Programa de actividades extraescolares",
  "Programa de salud y bienestar",
  "Programa de tratamiento del alcoholismo",
  "Programa de viviendas para personas de bajos ingresos",
  "Promotora inmobiliaria",
  "Propiedad de arrendatario",
  "Prostodoncista",
  "Protectora de animales",
  "Proveedor de agua embotellada",
  "Proveedor de alarmas de coche",
  "Proveedor de alarmas de incendio",
  "Proveedor de aluminio",
  "Proveedor de articulos de cuero",
  "Proveedor de atracciones",
  "Proveedor de basculas",
  "Proveedor de bloques de cristal",
  "Proveedor de buzones de correo",
  "Proveedor de calcomanias",
  "Proveedor de cartuchos de toner",
  "Proveedor de cilindros de gas",
  "Proveedor de cojinetes",
  "Proveedor de complementos para camiones",
  "Proveedor de compresores neumaticos",
  "Proveedor de contenedores",
  "Proveedor de cubiertas para embarcaciones",
  "Proveedor de depositos para recoger el agua de lluvia",
  "Proveedor de energia ecologica",
  "Proveedor de equipos agricolas",
  "Proveedor de equipos audiovisuales",
  "Proveedor de equipos de ablandamiento de agua",
  "Proveedor de equipos de calefaccion",
  "Proveedor de equipos de control de la diabetes",
  "Proveedor de equipos de energia solar",
  "Proveedor de equipos de explotacion lechera",
  "Proveedor de equipos de ferrocarril",
  "Proveedor de equipos de fisioterapia",
  "Proveedor de equipos de iluminacion de escenarios",
  "Proveedor de equipos de laboratorio",
  "Proveedor de equipos de movilidad",
  "Proveedor de equipos de oficina",
  "Proveedor de equipos de perforacion",
  "Proveedor de equipos de radiografia",
  "Proveedor de equipos industriales de vacio",
  "Proveedor de equipos para cultivos hidroponicos",
  "Proveedor de equipos para discapacitados",
  "Proveedor de equipos para fabricas",
  "Proveedor de equipos para tiendas",
  "Proveedor de equipos para videoconferencia",
  "Proveedor de equipos para yacimientos petroliferos",
  "Proveedor de fertilizantes",
  "Proveedor de fibra de vidrio",
  "Proveedor de gomaespuma",
  "Proveedor de GPS",
  "Proveedor de granito",
  "Proveedor de hielo",
  "Proveedor de hielo seco",
  "Proveedor de hormigon preparado",
  "Proveedor de huevos",
  "Proveedor de instrumentos de medida",
  "Proveedor de lacteos",
  "Proveedor de lentes de contacto",
  "Proveedor de mangueras",
  "Proveedor de maquinaria de construccion",
  "Proveedor de maquinas de metal",
  "Proveedor de marcos de aluminio",
  "Proveedor de marcos de madera",
  "Proveedor de materiales abrasivos",
  "Proveedor de materiales de construccion",
  "Proveedor de moldeo",
  "Proveedor de neveras comerciales",
  "Proveedor de ostras",
  "Proveedor de peces para estanques",
  "Proveedor de plantas artificiales",
  "Proveedor de productos de belleza",
  "Proveedor de productos de caucho",
  "Proveedor de productos de limpieza",
  "Proveedor de productos para cerrar",
  "Proveedor de productos promocionales",
  "Proveedor de propano",
  "Proveedor de puertas",
  "Proveedor de puertas para garaje",
  "Proveedor de repuestos de carroceria de automoviles",
  "Proveedor de repuestos de electrodomesticos",
  "Proveedor de resortes",
  "Proveedor de semillas",
  "Proveedor de servicios de asistencia juridica",
  "Proveedor de servicios de Internet",
  "Proveedor de servicios de telecomunicaciones",
  "Proveedor de sistemas de agua caliente",
  "Proveedor de sistemas de proteccion contra incendios",
  "Proveedor de sistemas de seguridad",
  "Proveedor de sistemas solares de agua caliente",
  "Proveedor de sobres",
  "Proveedor de tapacubos",
  "Proveedor de toldos",
  "Proveedor de tuberias",
  "Proveedor de ventanas",
  "Proveedor mayorista de alimentos",
  "Proveedores de la industria metalurgica",
  "Proveedores de sabores, fragancias y aromas",
  "Pruebas de consumo de drogas",
  "Psicologo",
  "Psicologo infantil",
  "Psicoterapeuta",
  "Psiquiatra",
  "Pub",
  "Pub irlandes",
  "Pub restaurante",
  "Publicidad de correo directo",
  "Puente",
  "Puerto deportivo",
  "Puesto de cafe",
  "Puesto de primeros auxilios",
  "Puesto fronterizo",
  "Punto de alquiler automatico de peliculas",
  "Punto de alquiler automatico de videojuegos",
  "Punto sanitario autoservicio",
  "Queseria",
  "Quiosco",
  "Quiosco de recarga para moviles",
  "Quiropractico",
  "Radiologia odontologica",
  "Radiologo",
  "Rafting",
  "Rampa para embarcaciones",
  "Rancho ganadero",
  "Recinto ferial",
  "Recinto para eventos",
  "Rectoria",
  "Recursos naturales renovables para el medio ambiente",
  "Refineria de petroleo",
  "Reflexologia",
  "Reformas",
  "Reformas de banos",
  "Reformas de cocinas",
  "Refugio de vida salvaje",
  "Refugio para animales",
  "Registro civil",
  "Registro de la propiedad",
  "Registro de la propiedad intelectual",
  "Registro mercantil",
  "Relojeria",
  "Reparacion de camas de agua",
  "Reposteria china",
  "Representante comercial",
  "Reserva de fauna salvaje",
  "Reserva nacional",
  "Reserva natural",
  "Residencia",
  "Residencia canina",
  "Residencia de ancianos",
  "Residencia de cuidados paliativos",
  "Residencia de estudiantes",
  "Residencia geriatrica",
  "Residencia militar",
  "Restauracion de danos por agua",
  "Restaurant konkani",
  "Restaurant shabu-shabu",
  "Restaurante",
  "Restaurante afgano",
  "Restaurante africano",
  "Restaurante aleman",
  "Restaurante americano",
  "Restaurante andaluz",
  "Restaurante argentino",
  "Restaurante armenio",
  "Restaurante asiatico",
  "Restaurante asturiano",
  "Restaurante australiano",
  "Restaurante austriaco",
  "Restaurante balines",
  "Restaurante bangladesi",
  "Restaurante belga",
  "Restaurante betawi",
  "Restaurante birmano",
  "Restaurante brasileno",
  "Restaurante britanico",
  "Restaurante bulgaro",
  "Restaurante caboverdiano",
  "Restaurante camboyano",
  "Restaurante canadiense",
  "Restaurante cantabro",
  "Restaurante cantones",
  "Restaurante caribeno",
  "Restaurante checo",
  "Restaurante chileno",
  "Restaurante chino",
  "Restaurante chino de comida para llevar",
  "Restaurante colombiano",
  "Restaurante con sala de baile",
  "Restaurante coreano",
  "Restaurante costarricense",
  "Restaurante croata",
  "Restaurante cubano",
  "Restaurante danes",
  "Restaurante de alas de pollo",
  "Restaurante de alta cocina",
  "Restaurante de bakso",
  "Restaurante de barbacoa coreana",
  "Restaurante de barbacoa mongola",
  "Restaurante de brunch",
  "Restaurante de burritos",
  "Restaurante de casqueria",
  "Restaurante de Cerdena",
  "Restaurante de champon",
  "Restaurante de chuletas con miso",
  "Restaurante de cocina castellana",
  "Restaurante de cocina catalana",
  "Restaurante de cocina centroamericana",
  "Restaurante de cocina Chettinad",
  "Restaurante de cocina contemporanea britanica",
  "Restaurante de cocina contemporanea de Luisiana",
  "Restaurante de cocina contemporanea europea",
  "Restaurante de cocina contemporanea francesa",
  "Restaurante de cocina criolla",
  "Restaurante de cocina de Africa Oriental",
  "Restaurante de cocina de Dongbei",
  "Restaurante de cocina de Europa del Este",
  "Restaurante de cocina de Florida",
  "Restaurante de cocina de Huaiyang",
  "Restaurante de cocina de Hubei",
  "Restaurante de cocina de Hunan",
  "Restaurante de cocina de Karnataka",
  "Restaurante de cocina de Nueva Inglaterra",
  "Restaurante de cocina de Oriente Medio",
  "Restaurante de cocina de Shanxi",
  "Restaurante de cocina de Sichuan",
  "Restaurante de cocina del norte de Italia",
  "Restaurante de cocina del Sudeste Asiatico",
  "Restaurante de cocina del sur de Italia",
  "Restaurante de cocina del suroeste de Francia",
  "Restaurante de cocina espanola",
  "Restaurante de cocina europea",
  "Restaurante de cocina francesa especializado en filetes",
  "Restaurante de cocina mandarina",
  "Restaurante de cocina panasiatica",
  "Restaurante de cocina panlatinoamericana",
  "Restaurante de cocina provenzal",
  "Restaurante de cocina romana",
  "Restaurante de cocina shanghainesa",
  "Restaurante de cocina sudamericana",
  "Restaurante de cocina surasiatica",
  "Restaurante de cocina toscana",
  "Restaurante de cocina valenciana",
  "Restaurante de comida alsaciana",
  "Restaurante de comida batak",
  "Restaurante de comida californiana",
  "Restaurante de comida casera",
  "Restaurante de comida continental",
  "Restaurante de comida cruda",
  "Restaurante de comida de Africa Occidental",
  "Restaurante de comida de Celebes Meridional",
  "Restaurante de comida de Java Central",
  "Restaurante de comida de Java Oriental",
  "Restaurante de comida de la Cuenca del Pacifico",
  "Restaurante de comida de la region de Berry",
  "Restaurante de comida de la region de Chesapeake",
  "Restaurante de comida de la region italiana de Las Marcas",
  "Restaurante de comida de Manado",
  "Restaurante de comida de Padang",
  "Restaurante de comida del Atlantico Medio de Estados Unidos",
  "Restaurante de comida del Noroeste del Pacifico de Canada",
  "Restaurante de comida del Noroeste del Pacifico de Estados Unidos",
  "Restaurante de comida del sur de Estados Unidos",
  "Restaurante de comida del suroeste de Estados Unidos",
  "Restaurante de comida kazaja",
  "Restaurante de comida madrilena",
  "Restaurante de comida occidental japonesa",
  "Restaurante de comida para llevar",
  "Restaurante de comida quebequesa",
  "Restaurante de comida rapida",
  "Restaurante de comida rapida al estilo de Hong Kong",
  "Restaurante de comida saludable",
  "Restaurante de comida seychelense",
  "Restaurante de comida sin gluten",
  "Restaurante de comida tradicional americana",
  "Restaurante de cuscus",
  "Restaurante de desayunos",
  "Restaurante de dumplings",
  "Restaurante de falafeles",
  "Restaurante de fideos chinos",
  "Restaurante de fideos dan dan",
  "Restaurante de fideos frios",
  "Restaurante de fish & chips",
  "Restaurante de fondues",
  "Restaurante de fusion",
  "Restaurante de gachas",
  "Restaurante de gyros",
  "Restaurante de gyudon",
  "Restaurante de hot pot",
  "Restaurante de ikan bakar",
  "Restaurante de kashmiri",
  "Restaurante de katsudon",
  "Restaurante de kushiage y kushikatsu",
  "Restaurante de Liguria",
  "Restaurante de Lombardia",
  "Restaurante de marisco donburi",
  "Restaurante de monjayaki",
  "Restaurante de murtabak",
  "Restaurante de nasi goreng",
  "Restaurante de nasi uduk",
  "Restaurante de pancakes",
  "Restaurante de pecel lele",
  "Restaurante de pempek",
  "Restaurante de perritos calientes",
  "Restaurante de pho",
  "Restaurante de platos de carne",
  "Restaurante de postres",
  "Restaurante de postres japoneses",
  "Restaurante de ryotei",
  "Restaurante de satay",
  "Restaurante de sfiha",
  "Restaurante de Singapur",
  "Restaurante de sopas",
  "Restaurante de soto ayam",
  "Restaurante de Sri Lanka",
  "Restaurante de suppon",
  "Restaurante de sushi",
  "Restaurante de sushi con cinta transportadora",
  "Restaurante de syokudo y teishoku",
  "Restaurante de tempura de donburi",
  "Restaurante de tofu",
  "Restaurante de udon",
  "Restaurante del Piamonte",
  "Restaurante dominicano",
  "Restaurante ecuatoriano",
  "Restaurante egipcio",
  "Restaurante en barco de vapor",
  "Restaurante eritreo",
  "Restaurante escandinavo",
  "Restaurante especializado en alta cocina francesa",
  "Restaurante especializado en anago",
  "Restaurante especializado en barbacoa",
  "Restaurante especializado en casqueria",
  "Restaurante especializado en chanko",
  "Restaurante especializado en cheesesteak",
  "Restaurante especializado en chuletas",
  "Restaurante especializado en cocina americana moderna",
  "Restaurante especializado en cocina cajun",
  "Restaurante especializado en cocina moderna latinoamericana",
  "Restaurante especializado en comida eclectica",
  "Restaurante especializado en comida nativa americana",
  "Restaurante especializado en costillas al estilo coreano",
  "Restaurante especializado en crustaceos y moluscos",
  "Restaurante especializado en curry japones",
  "Restaurante especializado en dim sum",
  "Restaurante especializado en dojo",
  "Restaurante especializado en fideos",
  "Restaurante especializado en fideos de soba",
  "Restaurante especializado en filetes",
  "Restaurante especializado en fugu",
  "Restaurante especializado en fusion asiatica",
  "Restaurante especializado en kaiseki",
  "Restaurante especializado en kushiyaki",
  "Restaurante especializado en la cocina holandesa de Pensilvania",
  "Restaurante especializado en lengua",
  "Restaurante especializado en obanzai",
  "Restaurante especializado en oden",
  "Restaurante especializado en okonomiyaki",
  "Restaurante especializado en platos pequenos",
  "Restaurante especializado en Po' boy",
  "Restaurante especializado en pollo",
  "Restaurante especializado en raclette",
  "Restaurante especializado en ramen",
  "Restaurante especializado en rape",
  "Restaurante especializado en sandwich submarino",
  "Restaurante especializado en soul food",
  "Restaurante especializado en sukiyaki y shabu shabu",
  "Restaurante especializado en sundae",
  "Restaurante especializado en tapas",
  "Restaurante especializado en tempura",
  "Restaurante especializado en teppanyaki",
  "Restaurante especializado en ternera al estilo coreano",
  "Restaurante especializado en tonkatsu",
  "Restaurante especializado en unagi",
  "Restaurante especializado en yakiniku",
  "Restaurante especializado en yakitori",
  "Restaurante etiope",
  "Restaurante etnico",
  "Restaurante extremeno",
  "Restaurante familiar",
  "Restaurante filipino",
  "Restaurante finlandes",
  "Restaurante frances",
  "Restaurante gales",
  "Restaurante gallego",
  "Restaurante georgiano",
  "Restaurante goano",
  "Restaurante griego",
  "Restaurante guatemalteco",
  "Restaurante haitiano",
  "Restaurante halal",
  "Restaurante hawaiano",
  "Restaurante holandes",
  "Restaurante hondureno",
  "Restaurante hungaro",
  "Restaurante indio",
  "Restaurante indio de curry",
  "Restaurante indonesio",
  "Restaurante ingles",
  "Restaurante irlandes",
  "Restaurante islandes",
  "Restaurante israeli",
  "Restaurante italiano",
  "Restaurante izakaya",
  "Restaurante jamaicano",
  "Restaurante japones",
  "Restaurante japones al estilo de Kioto",
  "Restaurante japones autentico",
  "Restaurante javanes",
  "Restaurante judio",
  "Restaurante kosher",
  "Restaurante laosiano",
  "Restaurante latinoamericano",
  "Restaurante libanes",
  "Restaurante lituano",
  "Restaurante macrobiotico",
  "Restaurante malayo",
  "Restaurante mallorquin",
  "Restaurante maltes",
  "Restaurante marroqui",
  "Restaurante mediterraneo",
  "Restaurante mexicano",
  "Restaurante napolitano",
  "Restaurante navarro",
  "Restaurante neozelandes",
  "Restaurante nepali",
  "Restaurante nicaraguense",
  "Restaurante norafricano",
  "Restaurante noruego",
  "Restaurante occidental",
  "Restaurante organico",
  "Restaurante paquistani",
  "Restaurante paraguayo",
  "Restaurante persa",
  "Restaurante peruano",
  "Restaurante polaco",
  "Restaurante polinesio",
  "Restaurante portugues",
  "Restaurante puertorriqueno",
  "Restaurante punjabi",
  "Restaurante regional japones",
  "Restaurante rumano",
  "Restaurante ruso",
  "Restaurante salvadoreno",
  "Restaurante serbio",
  "Restaurante siciliano",
  "Restaurante sirio",
  "Restaurante sudafricano",
  "Restaurante sueco",
  "Restaurante suizo",
  "Restaurante sukyaki",
  "Restaurante sundanes",
  "Restaurante surinames",
  "Restaurante tailandes",
  "Restaurante taiwanes",
  "Restaurante takoyaki",
  "Restaurante tex-mex",
  "Restaurante tunecino",
  "Restaurante turco",
  "Restaurante turcomano",
  "Restaurante ucraniano",
  "Restaurante uruguayo",
  "Restaurante uzbeko",
  "Restaurante vasco",
  "Restaurante vegano",
  "Restaurante vegetariano",
  "Restaurante veneciano",
  "Restaurante venezolano",
  "Restaurante vietnamita",
  "Restaurante yemeni",
  "Reumatologo",
  "Rodeo",
  "Rugby",
  "Ruta por explotaciones agricolas",
  "Sacem",
  "Sala de baile",
  "Sala de banquetes",
  "Sala de billares",
  "Sala de conciertos",
  "Sala de curlin",
  "Sala de espera",
  "Sala de frutas",
  "Sala de pachinko",
  "Sala de tiro con arco",
  "Sala infantil",
  "Sala para jovenes",
  "Salon de bodas",
  "Salon de esgrima",
  "Salon de mah-jong",
  "Salon de manicura y pedicura",
  "Salon de reflexoterapia",
  "Salon de te",
  "Salon para eventos",
  "Salon recreativo",
  "Sambodromo",
  "Santuario",
  "Santuario de los pilares de la ciudad",
  "Santuario sintoista",
  "Sastre",
  "Sastre a medida",
  "Sastre para hombres",
  "Sauna",
  "Sauna publica",
  "Secretaria municipal",
  "Sede militar",
  "Seguridad y salud ocupacional",
  "Seitai",
  "Seminario",
  "Seminario religioso",
  "Serigrafia",
  "Servicio agricola",
  "Servicio de acabado de suelos",
  "Servicio de acogida familiar",
  "Servicio de administracion de empresas",
  "Servicio de adopcion de mascotas",
  "Servicio de aerografia",
  "Servicio de afilado",
  "Servicio de afilado de patines",
  "Servicio de afilado de sierras",
  "Servicio de afinacion de pianos",
  "Servicio de alineacion de ruedas",
  "Servicio de alojamiento vacacional",
  "Servicio de alquiler de aeronaves",
  "Servicio de alquiler de bicicletas",
  "Servicio de alquiler de buzones de correo",
  "Servicio de alquiler de casas flotantes",
  "Servicio de alquiler de coches",
  "Servicio de alquiler de disfraces",
  "Servicio de alquiler de embarcaciones",
  "Servicio de alquiler de equipos de oficina",
  "Servicio de alquiler de equipos para deportes acuaticos",
  "Servicio de alquiler de equipos para fiestas",
  "Servicio de alquiler de equipos para la construccion",
  "Servicio de alquiler de escuteres",
  "Servicio de alquiler de herramientas",
  "Servicio de alquiler de instrumentos musicales",
  "Servicio de alquiler de kayaks y canoas",
  "Servicio de alquiler de mobiliario",
  "Servicio de alquiler de motos de nieve",
  "Servicio de alquiler de remolques",
  "Servicio de alquiler de tiendas",
  "Servicio de ambulancias",
  "Servicio de analisis de suelos",
  "Servicio de antenas",
  "Servicio de aromaterapia",
  "Servicio de arrendamiento de automoviles",
  "Servicio de asesoramiento crediticio",
  "Servicio de asesoramiento fiscal",
  "Servicio de asesoria al consumidor",
  "Servicio de asistencia sanitaria domiciliaria",
  "Servicio de atencion al cliente de electrodomesticos",
  "Servicio de ayuda para cobros de menor cuantia",
  "Servicio de bordado",
  "Servicio de busqueda de abogado",
  "Servicio de busqueda de companeros de piso",
  "Servicio de busqueda de medico",
  "Servicio de cambio de aceite",
  "Servicio de cartografia",
  "Servicio de catering",
  "Servicio de certificados medicos",
  "Servicio de chapa y pintura",
  "Servicio de citas",
  "Servicio de clases particulares",
  "Servicio de cobro de cheques",
  "Servicio de comercio electronico",
  "Servicio de conserjeria",
  "Servicio de contenedores",
  "Servicio de contestador",
  "Servicio de control de animales",
  "Servicio de control de aves",
  "Servicio de copia e impresion de planos",
  "Servicio de corte por chorro de agua",
  "Servicio de cremacion",
  "Servicio de cuidado de viviendas",
  "Servicio de dactiloscopia",
  "Servicio de depilacion",
  "Servicio de depilacion por electrolisis",
  "Servicio de deteccion de amianto",
  "Servicio de distribucion",
  "Servicio de duplicacion de llaves",
  "Servicio de edicion de video",
  "Servicio de edicion grafica",
  "Servicio de ejecuciones hipotecarias",
  "Servicio de eliminacion de grafitis",
  "Servicio de eliminacion de nieve",
  "Servicio de eliminacion de tatuajes",
  "Servicio de embarque de mascotas",
  "Servicio de emergencias",
  "Servicio de entrega de compra a distancia",
  "Servicio de esqui acuatico",
  "Servicio de estampado de metales",
  "Servicio de estampado en relieve",
  "Servicio de facturacion medica",
  "Servicio de fax",
  "Servicio de ferry",
  "Servicio de fianzas",
  "Servicio de fiestas infantiles",
  "Servicio de gestion de aguas residuales",
  "Servicio de gestion de residuos",
  "Servicio de giros bancarios",
  "Servicio de grua",
  "Servicio de guardias de seguridad",
  "Servicio de hipnoterapia",
  "Servicio de impermeabilizacion",
  "Servicio de impresion de invitaciones",
  "Servicio de informatica",
  "Servicio de insolvencia",
  "Servicio de instalacion de puestos",
  "Servicio de instalacion de suelos de madera",
  "Servicio de instalacion de ventanas",
  "Servicio de instalacion electrica",
  "Servicio de inversiones",
  "Servicio de jardineria",
  "Servicio de laminado",
  "Servicio de lanzadera",
  "Servicio de lavado a presion",
  "Servicio de lavado de coches",
  "Servicio de lavanderia",
  "Servicio de limpieza de alfombras",
  "Servicio de limpieza de automoviles",
  "Servicio de limpieza de calzado",
  "Servicio de limpieza de canalones",
  "Servicio de limpieza de conductos de aire",
  "Servicio de limpieza de cuero",
  "Servicio de limpieza de piscinas",
  "Servicio de limpieza de playas",
  "Servicio de limpieza de tapiceria",
  "Servicio de limpieza de ventanas",
  "Servicio de limpieza domestica",
  "Servicio de limpieza por chorro de arena",
  "Servicio de limusinas",
  "Servicio de logistica",
  "Servicio de mantenimiento de piscinas",
  "Servicio de marketing por Internet",
  "Servicio de mecanografia",
  "Servicio de mensajeria",
  "Servicio de mudanzas",
  "Servicio de mudanzas y almacenamiento",
  "Servicio de naturalizacion e inmigracion",
  "Servicio de panales",
  "Servicio de paseo a caballo",
  "Servicio de paseo en carruaje",
  "Servicio de planificacion de reuniones",
  "Servicio de plantas para interior",
  "Servicio de polarizacion de ventanas",
  "Servicio de poligrafo",
  "Servicio de produccion de video",
  "Servicio de proteccion de la mujer",
  "Servicio de pruebas de paternidad",
  "Servicio de pruebas educativas",
  "Servicio de quiebras",
  "Servicio de reacondicionamiento de motores",
  "Servicio de recogida de basura",
  "Servicio de recubrimiento en polvo",
  "Servicio de recuperacion de datos",
  "Servicio de regimen de pension de ganado",
  "Servicio de registros contables",
  "Servicio de rehabilitacion de la fauna",
  "Servicio de remolque",
  "Servicio de reparacion de aire acondicionado",
  "Servicio de reparacion de audifonos",
  "Servicio de reparacion de basculas",
  "Servicio de reparacion de camaras de video",
  "Servicio de reparacion de compresores de aire",
  "Servicio de reparacion de cortadoras de cesped",
  "Servicio de reparacion de cristales",
  "Servicio de reparacion de cuero",
  "Servicio de reparacion de electrodomesticos",
  "Servicio de reparacion de equipos de musica",
  "Servicio de reparacion de equipos de video",
  "Servicio de reparacion de fibra de vidrio",
  "Servicio de reparacion de fotocopiadoras",
  "Servicio de reparacion de hornos",
  "Servicio de reparacion de impresoras",
  "Servicio de reparacion de jacuzzis",
  "Servicio de reparacion de joyas",
  "Servicio de reparacion de lamparas",
  "Servicio de reparacion de lavadoras y secadoras",
  "Servicio de reparacion de maletas",
  "Servicio de reparacion de maquinaria agricola",
  "Servicio de reparacion de maquinas de coser",
  "Servicio de reparacion de maquinas de escribir",
  "Servicio de reparacion de microondas",
  "Servicio de reparacion de motores de baja potencia",
  "Servicio de reparacion de neveras",
  "Servicio de reparacion de ordenadores",
  "Servicio de reparacion de parabrisas y pantallas",
  "Servicio de reparacion de pequenos electrodomesticos",
  "Servicio de reparacion de pianos",
  "Servicio de reparacion de radiadores",
  "Servicio de reparacion de radiadores de automoviles",
  "Servicio de reparacion de relojes",
  "Servicio de reparacion de reproductores de video",
  "Servicio de reparacion de sillas de ruedas",
  "Servicio de reparacion de sistemas electricos para automoviles",
  "Servicio de reparacion de sistemas hidraulicos",
  "Servicio de reparacion de telefonos",
  "Servicio de reparacion de televisores",
  "Servicio de rescate de animales",
  "Servicio de restauracion artistica",
  "Servicio de restauracion de automoviles",
  "Servicio de restauracion de danos por incendios",
  "Servicio de restauracion de edificios",
  "Servicio de restauracion de fotos",
  "Servicio de restauracion de muebles antiguos",
  "Servicio de restauracion de munecas",
  "Servicio de salud mental",
  "Servicio de salud ocupacional",
  "Servicio de saneamiento",
  "Servicio de seguridad",
  "Servicio de seguridad contra incendios",
  "Servicio de seguridad informatica",
  "Servicio de sistemas septicos",
  "Servicio de taxis",
  "Servicio de tecnologia de eventos",
  "Servicio de telegramas musicales",
  "Servicio de telemarketing",
  "Servicio de transcripcion",
  "Servicio de transcripcion medica",
  "Servicio de transferencias de dinero",
  "Servicio de transporte",
  "Servicio de transporte con acompanante",
  "Servicio de transporte de mercancias",
  "Servicio de transporte para discapacitados",
  "Servicio de traslado de pianos",
  "Servicio de tratamiento del cabello",
  "Servicio de triturado",
  "Servicio de urgencias dentales",
  "Servicio de urgencias veterinarias",
  "Servicio forestal",
  "Servicio meteorologico",
  "Servicio postal",
  "Servicio tecnico",
  "Servicios de clarividencia",
  "Servicios de CV",
  "Servicios de deposito de garantia",
  "Servicios de diseno",
  "Servicios de documentacion",
  "Servicios de empresa a empresa",
  "Servicios de ferrocarril",
  "Servicios de limpieza",
  "Servicios de mantenimiento arboreo",
  "Servicios legales",
  "Servicios medicos locales",
  "Servicios nupciales",
  "Servicios para sordos",
  "Sex shop",
  "Sidreria",
  "Sinagoga",
  "Sinagoga conservadora",
  "Sinagoga mesianica",
  "Sinagoga ortodoxa",
  "Sinagoga reformista",
  "Sindicato",
  "Sitio del Superfondo",
  "Skate park",
  "Snack bar",
  "Sociedad de credito hipotecario",
  "Sociedad de viviendas",
  "Sociedad historica",
  "Societe de Flocage",
  "Soldador",
  "Sombrereria",
  "Soplador de vidrio",
  "Soporte y servicios informaticos",
  "Spa",
  "Spa con piedras calientes",
  "Spa de dia",
  "Spa terapeutico",
  "Spa y gimnasio",
  "Subastas de coches",
  "Subestacion electrica",
  "Suministro y fabricacion de alimentos",
  "Supermercado",
  "Supermercado asiatico",
  "Supermercado chino",
  "Supermercado coreano",
  "Supermercado de descuentos",
  "Supermercado de muebles",
  "Supermercado indio",
  "Supermercado industrial",
  "Supermercado italiano",
  "Supermercado japones",
  "Supermercado kosher",
  "Supermercado mexicano",
  "Taberna",
  "Taller de amortiguadores",
  "Taller de automoviles",
  "Taller de bicicletas",
  "Taller de camiones",
  "Taller de chapa y pintura",
  "Taller de costura",
  "Taller de cristales para automoviles",
  "Taller de encuadernacion",
  "Taller de frenos",
  "Taller de instalacion de puertas y ventanas",
  "Taller de maquinaria",
  "Taller de metalurgia",
  "Taller de propulsores",
  "Taller de reparacion de aspiradoras",
  "Taller de reparacion de autocaravanas",
  "Taller de reparacion de automoviles",
  "Taller de reparacion de botas",
  "Taller de reparacion de camaras",
  "Taller de reparacion de embarcaciones",
  "Taller de reparacion de equipos audiovisuales",
  "Taller de reparacion de escuteres",
  "Taller de reparacion de herramientas",
  "Taller de reparacion de instrumentos musicales",
  "Taller de reparacion de mobiliario",
  "Taller de reparacion de motores diesel",
  "Taller de reparacion de motores electricos",
  "Taller de reparacion de motos",
  "Taller de reparacion de remolques",
  "Taller de reparacion de tractores",
  "Taller de reparacion de vehiculos todoterreno",
  "Taller de reparaciones electricas",
  "Taller de revision de automoviles",
  "Taller mecanico",
  "Tapiceria",
  "Tapiceria para automoviles",
  "Taqueria",
  "Taquigrafo judicial",
  "Taquilla accionada por moneda",
  "Taquilla para paquetes",
  "Tasador",
  "Tasador de bienes inmuebles",
  "Tasador de joyas",
  "Tasador inmobiliario",
  "Taxi aereo",
  "Taxidermista",
  "Te de burbujas",
  "Teatro",
  "Teatro de marionetas",
  "Teatro flamenco",
  "Teatro infantil",
  "Tejeduria",
  "Teleferico de montana",
  "Television de circuito cerrado",
  "Templo Baha'i",
  "Templo budista",
  "Templo de parsis",
  "Templo hindu",
  "Templo jainista",
  "Templo taoista",
  "Terapeuta de drenaje linfatico",
  "Terapeuta de reiki",
  "Terapeuta de retroalimentacion biologica",
  "Terapeuta ocupacional",
  "Terapia craneosacral",
  "Teteria tradicional",
  "Tienda de abrigos",
  "Tienda de abrigos de cuero",
  "Tienda de abrigos de piel",
  "Tienda de accesorios de moda",
  "Tienda de accesorios informaticos",
  "Tienda de accesorios para automoviles",
  "Tienda de accesorios para camiones",
  "Tienda de accesorios para moviles",
  "Tienda de accesorios para ventanas",
  "Tienda de acuarios",
  "Tienda de aeromodelismo",
  "Tienda de alarmas antirrobo",
  "Tienda de alfombras",
  "Tienda de alfombras orientales",
  "Tienda de alimentacion",
  "Tienda de alimentos naturales",
  "Tienda de alimentos organicos",
  "Tienda de alimentos para animales",
  "Tienda de alquilar de equipos de musica",
  "Tienda de alquiler de videojuegos",
  "Tienda de alta costura",
  "Tienda de animales",
  "Tienda de antiguedades",
  "Tienda de apuestas hipicas",
  "Tienda de armarios",
  "Tienda de aromaterapia",
  "Tienda de arreglos de ropa",
  "Tienda de arreos",
  "Tienda de arroz",
  "Tienda de articulos budistas",
  "Tienda de articulos de aseo personal",
  "Tienda de articulos de camping",
  "Tienda de articulos de caza",
  "Tienda de articulos de caza y pesca",
  "Tienda de articulos de cocina",
  "Tienda de articulos de cricket",
  "Tienda de articulos de cristal",
  "Tienda de articulos de danza",
  "Tienda de articulos de fiesta",
  "Tienda de articulos de fontaneria",
  "Tienda de articulos de futbol",
  "Tienda de articulos de golf",
  "Tienda de articulos de hosteleria",
  "Tienda de articulos de magia",
  "Tienda de articulos de natacion",
  "Tienda de articulos de paintball",
  "Tienda de articulos de pesca",
  "Tienda de articulos de rugby",
  "Tienda de articulos de seda",
  "Tienda de articulos de segunda mano",
  "Tienda de articulos de tenis",
  "Tienda de articulos deportivos coleccionables",
  "Tienda de articulos domesticos asiaticos",
  "Tienda de articulos ortopedicos",
  "Tienda de articulos para barbacoas",
  "Tienda de articulos para bebes",
  "Tienda de articulos para billares",
  "Tienda de articulos para bodas",
  "Tienda de articulos para correr",
  "Tienda de articulos para decoracion en pasteleria",
  "Tienda de articulos para el hogar",
  "Tienda de articulos para esqui acuatico",
  "Tienda de articulos para flamenco",
  "Tienda de articulos para hacer cerveza",
  "Tienda de articulos para pintura",
  "Tienda de articulos para piscinas",
  "Tienda de articulos para saunas",
  "Tienda de articulos pirotecnicos",
  "Tienda de articulos premama y de bebe",
  "Tienda de articulos relacionados con el gas",
  "Tienda de articulos religiosos",
  "Tienda de aspiradoras",
  "Tienda de audifonos",
  "Tienda de automovilismo",
  "Tienda de aves de corral",
  "Tienda de azulejos",
  "Tienda de bagels",
  "Tienda de banderas",
  "Tienda de baterias",
  "Tienda de baterias para automovil",
  "Tienda de bebidas alcoholicas",
  "Tienda de belleza y salud",
  "Tienda de bicicletas",
  "Tienda de bicicletas de segunda mano",
  "Tienda de bisuteria",
  "Tienda de boligrafos",
  "Tienda de bollos al vapor",
  "Tienda de bolsos",
  "Tienda de bordados",
  "Tienda de botas",
  "Tienda de botas de fieltro",
  "Tienda de bricolaje",
  "Tienda de butsudan",
  "Tienda de cachimbas",
  "Tienda de cafe",
  "Tienda de cajas fuertes",
  "Tienda de cajas musicales",
  "Tienda de calderas",
  "Tienda de camaras",
  "Tienda de camas de agua",
  "Tienda de camisetas",
  "Tienda de camisetas personalizadas",
  "Tienda de cannabis",
  "Tienda de canoas y kayaks",
  "Tienda de cartas coleccionables",
  "Tienda de CD de segunda mano",
  "Tienda de CDs",
  "Tienda de cebos",
  "Tienda de ceramica",
  "Tienda de cerveza",
  "Tienda de cestas de regalo",
  "Tienda de chimeneas",
  "Tienda de cinturones",
  "Tienda de colchas",
  "Tienda de coleccionables",
  "Tienda de coleccionismo",
  "Tienda de collage",
  "Tienda de comestibles mayorista",
  "Tienda de comestibles, periodicos y medicamentos",
  "Tienda de cometas",
  "Tienda de comics",
  "Tienda de componentes electronicos",
  "Tienda de congelados",
  "Tienda de cortadoras de cesped",
  "Tienda de cortinas",
  "Tienda de cosmeticos",
  "Tienda de costura",
  "Tienda de cristales",
  "Tienda de cristales y espejos",
  "Tienda de cromos deportivos",
  "Tienda de cuberteria",
  "Tienda de cuentas",
  "Tienda de delicatessen",
  "Tienda de deportes",
  "Tienda de deportes al aire libre",
  "Tienda de descuento",
  "Tienda de discos",
  "Tienda de disfraces",
  "Tienda de donuts",
  "Tienda de dulces japoneses",
  "Tienda de DVD",
  "Tienda de DVD para adultos",
  "Tienda de ejes de transmision",
  "Tienda de electricidad",
  "Tienda de electrodomesticos",
  "Tienda de electrodomesticos de segunda mano",
  "Tienda de electronica",
  "Tienda de encimeras",
  "Tienda de enmarcacion",
  "Tienda de ensaladas",
  "Tienda de entretenimiento para la playa",
  "Tienda de envoltorios para regalos",
  "Tienda de equipaje",
  "Tienda de equipamiento y ropa para actividades al aire libre",
  "Tienda de equipos de banos",
  "Tienda de equipos de cine en casa",
  "Tienda de equipos de sonido",
  "Tienda de equipos estereo para automoviles",
  "Tienda de esmoquines",
  "Tienda de especias",
  "Tienda de espejos",
  "Tienda de esqui",
  "Tienda de estanterias",
  "Tienda de estufas de lena",
  "Tienda de excedentes",
  "Tienda de excedentes del ejercito y la marina",
  "Tienda de farmacos organicos",
  "Tienda de felicitaciones",
  "Tienda de Feng Shui",
  "Tienda de fiambres",
  "Tienda de figuritas",
  "Tienda de filatelia",
  "Tienda de flores secas",
  "Tienda de fotografia",
  "Tienda de frutos secos",
  "Tienda de futones",
  "Tienda de gafas de sol",
  "Tienda de galletas",
  "Tienda de globos",
  "Tienda de golosinas",
  "Tienda de guitarras",
  "Tienda de herramientas",
  "Tienda de herramientas y troqueles",
  "Tienda de Hua Gong",
  "Tienda de iluminacion",
  "Tienda de informatica",
  "Tienda de instrumentos de percusion",
  "Tienda de instrumentos musicales",
  "Tienda de instrumentos musicales de segunda mano",
  "Tienda de jacuzzis",
  "Tienda de jamones",
  "Tienda de juegos",
  "Tienda de juegos usados",
  "Tienda de kebabs",
  "Tienda de labores de punto",
  "Tienda de lana",
  "Tienda de lavadoras y secadoras",
  "Tienda de lenceria",
  "Tienda de letreros de neon",
  "Tienda de libros de segunda mano",
  "Tienda de libros juridicos",
  "Tienda de libros medicos",
  "Tienda de licores del estado",
  "Tienda de linoleo",
  "Tienda de loteria",
  "Tienda de magdalenas",
  "Tienda de mamparas de ducha",
  "Tienda de manualidades y bellas artes",
  "Tienda de mapas",
  "Tienda de maquinas de coser",
  "Tienda de marisco seco",
  "Tienda de material aeronautico",
  "Tienda de material de oficina",
  "Tienda de material deportivo",
  "Tienda de material escolar",
  "Tienda de material para artes marciales",
  "Tienda de material para DJ",
  "Tienda de material para mudanzas",
  "Tienda de material sanitario",
  "Tienda de materiales de aislamiento",
  "Tienda de materiales de embalaje",
  "Tienda de materiales para la construccion",
  "Tienda de materiales para mamposteria sin mortero",
  "Tienda de materiales para suelos",
  "Tienda de medicina china",
  "Tienda de medicinas naturales",
  "Tienda de minerales",
  "Tienda de miniaturas",
  "Tienda de mobiliario de cana",
  "Tienda de mobiliario de jardin",
  "Tienda de mobiliario de oficina",
  "Tienda de mobiliario de oficina usado",
  "Tienda de mobiliario infantil",
  "Tienda de mobiliario para bares y restaurantes",
  "Tienda de mobiliario para dormitorios",
  "Tienda de mobiliario sin acabado",
  "Tienda de moda de alta costura",
  "Tienda de modelismo",
  "Tienda de modelismo de trenes",
  "Tienda de monopatines",
  "Tienda de mosquiteras",
  "Tienda de motocicletas",
  "Tienda de motores electricos",
  "Tienda de motores fueraborda",
  "Tienda de moviles",
  "Tienda de muebles",
  "Tienda de muebles amish",
  "Tienda de muebles antiguos",
  "Tienda de muebles de cocina",
  "Tienda de muebles de exterior",
  "Tienda de muebles de pino",
  "Tienda de muebles de segunda mano",
  "Tienda de muebles rusticos",
  "Tienda de munecas",
  "Tienda de musica",
  "Tienda de neumaticos",
  "Tienda de neumaticos usados",
  "Tienda de neveras",
  "Tienda de nutricion deportiva",
  "Tienda de objetos arquitectonicos",
  "Tienda de objetos de mimbre",
  "Tienda de ordenadores de segunda mano",
  "Tienda de palomitas",
  "Tienda de pancartas publicitarias",
  "Tienda de papel tapiz",
  "Tienda de partituras",
  "Tienda de pasta",
  "Tienda de peces tropicales",
  "Tienda de pelucas",
  "Tienda de persianas",
  "Tienda de pianos",
  "Tienda de piercings",
  "Tienda de piercings y tatuajes",
  "Tienda de piezas de automovil",
  "Tienda de pinturas",
  "Tienda de plantas de seda",
  "Tienda de porcelana",
  "Tienda de posteres",
  "Tienda de postres",
  "Tienda de pretzels",
  "Tienda de productos acrilicos",
  "Tienda de productos africanos",
  "Tienda de productos agricolas",
  "Tienda de productos australianos",
  "Tienda de productos de beisbol",
  "Tienda de productos de belleza",
  "Tienda de productos de chocolate",
  "Tienda de productos de indios americanos",
  "Tienda de productos de temporada",
  "Tienda de productos hawaianos",
  "Tienda de productos irlandeses",
  "Tienda de productos lacteos",
  "Tienda de productos mexicanos",
  "Tienda de productos navidenos",
  "Tienda de productos organicos",
  "Tienda de productos orientales",
  "Tienda de productos para mascotas",
  "Tienda de productos religiosos",
  "Tienda de puros",
  "Tienda de quimonos",
  "Tienda de radiadores",
  "Tienda de recarga de cartuchos de impresora",
  "Tienda de recuerdos",
  "Tienda de recuerdos de boda",
  "Tienda de refrescos",
  "Tienda de regalos",
  "Tienda de reparacion de ciclomotores",
  "Tienda de reparacion de telefonos moviles",
  "Tienda de reptiles",
  "Tienda de repuestos de automoviles usados",
  "Tienda de repuestos para automoviles",
  "Tienda de repuestos para coches de carreras",
  "Tienda de repuestos para motos",
  "Tienda de ropa",
  "Tienda de ropa de cama",
  "Tienda de ropa de deportes",
  "Tienda de ropa de hogar",
  "Tienda de ropa de hombre",
  "Tienda de ropa de mujer",
  "Tienda de ropa de playa",
  "Tienda de ropa de segunda mano",
  "Tienda de ropa de tallas grandes",
  "Tienda de ropa de trabajo",
  "Tienda de ropa de vestir",
  "Tienda de ropa del Oeste",
  "Tienda de ropa infantil",
  "Tienda de ropa interior",
  "Tienda de ropa para bebes",
  "Tienda de ropa para jovenes",
  "Tienda de ropa vintage",
  "Tienda de ruedas",
  "Tienda de segunda mano",
  "Tienda de sellos",
  "Tienda de sellos de caucho",
  "Tienda de senalizacion",
  "Tienda de serigrafia",
  "Tienda de silenciadores",
  "Tienda de sillas de ruedas",
  "Tienda de skate",
  "Tienda de snowboard",
  "Tienda de sofas",
  "Tienda de software",
  "Tienda de submarinismo",
  "Tienda de suministros a hoteles",
  "Tienda de suministros maritimos",
  "Tienda de suministros metafisicos",
  "Tienda de suministros para aerografia",
  "Tienda de suministros para airsoft",
  "Tienda de suministros para albanileria",
  "Tienda de suministros para autocaravanas",
  "Tienda de suministros para bolos",
  "Tienda de suministros para cubiertas y tejados",
  "Tienda de suministros para dardos",
  "Tienda de suministros para elaboracion de vinos",
  "Tienda de suministros para estanques",
  "Tienda de suministros para fotocopias",
  "Tienda de suministros para hockey",
  "Tienda de suministros para hornear",
  "Tienda de suministros para masajes",
  "Tienda de suministros para odontologia",
  "Tienda de suministros para paisajismo",
  "Tienda de suministros para peluqueria",
  "Tienda de suministros para policias",
  "Tienda de suministros para remolques",
  "Tienda de suministros para serigrafia",
  "Tienda de suministros para soldadura",
  "Tienda de suministros para teatros",
  "Tienda de suministros para tenis de mesa",
  "Tienda de suministros para trabajar la madera",
  "Tienda de suministros para vallas",
  "Tienda de suministros quirurgicos",
  "Tienda de surf",
  "Tienda de tamales",
  "Tienda de tartas",
  "Tienda de tartas de arroz",
  "Tienda de tatamis",
  "Tienda de te",
  "Tienda de techos corredizos para automoviles",
  "Tienda de telas",
  "Tienda de telescopios",
  "Tienda de tiro con arco",
  "Tienda de todo a 1 euro",
  "Tienda de tortitas de arroz",
  "Tienda de trajes tradicionales",
  "Tienda de transmisiones",
  "Tienda de trofeos",
  "Tienda de ultramarinos",
  "Tienda de uniformes",
  "Tienda de vaporizadores",
  "Tienda de vehiculos de segunda mano y de ocasion",
  "Tienda de venta de videos",
  "Tienda de ventanas de plastico",
  "Tienda de vestidos de novia",
  "Tienda de videojuegos",
  "Tienda de vinos",
  "Tienda de violines",
  "Tienda de vitaminas y suplementos",
  "Tienda de windsurf",
  "Tienda de zumos",
  "Tienda ecuestre",
  "Tienda especializada en camas",
  "Tienda general",
  "Tienda infantil",
  "Tienda japonesa de dulces economicos",
  "Tienda libre de impuestos",
  "Tienda naturista",
  "Tiende aire acondicionado",
  "Tintoreria",
  "Tobogan de verano",
  "Topografo",
  "Tostadores de cafe",
  "Trabajos en altura",
  "Traductor",
  "Transportista de viviendas prefabricadas",
  "Trasteros y almacenamiento",
  "Trust Bank",
  "Turoperador",
  "Unidad hospitalaria",
  "Universidad",
  "Universidad a distancia",
  "Universidad privada",
  "Universidad publica",
  "Urbanizacion",
  "Urologo",
  "Vaqueria",
  "Vendedor de entradas para eventos",
  "Vendedor mayorista de productos del campo",
  "Venta de caravanas y autocaravanas",
  "Venta de embarcaciones",
  "Venta de motocicletas de segunda mano",
  "Ventana de aluminio",
  "Vertedero",
  "Veterinario",
  "Vidente",
  "Videoclub",
  "Vinedo",
  "Vinoteca",
  "Vivero",
  "Vivero de arboles de Navidad",
  "Vivero de marisco",
  "Vivero forestal",
  "Vivero mayorista",
  "Yakatabune",
  "Yeshiva",
  "Yogurteria",
  "Zapateria",
  "Zapatero",
  "Zona de bajas emisiones",
  "Zona de barbacoa",
  "Zona de caza",
  "Zona de competicion de taekwondo",
  "Zona de eventos de tiro",
  "Zona de formacion de conductores",
  "Zona de levantamiento de pesas",
  "Zona de observacion de aves",
  "Zona de picnic",
  "Zona de piraguismo",
  "Zona de restauracion",
  "Zona de senderismo",
  "Zona Wi-Fi",
  "Zoo",
];

const fs = require("fs");

const processedCategories = categories
  .sort(function (a, b) {
    if (a.firstname < b.firstname) {
      return -1;
    }
    if (a.firstname > b.firstname) {
      return 1;
    }
    return 0;
  })
  .map((v, i) => {
    return { key: i + 1, value: v };
  });

fs.writeFileSync(
  "./src/output/categories.json",
  JSON.stringify({ categories: processedCategories }, null, 2)
);
